services:
    nginx:
        image: nginx:latest
        container_name: container_nginx
        restart: always
        tty: true
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./etc/docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - app_network
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: php:8-3-fpm
        container_name: container_app
        restart: always
        tty: true
        environment:
            APP_ENV: ${APP_ENV}
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
        networks:
            - app_network
    db:
        image: mysql:8.0.25
        container_name: container_db
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - container_db:/var/lib/mysql
        ports:
            - "3306:3306"
        extra_hosts:
            - host.docker.internal:host-gateway
        networks:
            - app_network

volumes:
    container_db:

networks:
    app_network:
        driver: bridge